volumes:
    postgres-data:
        external: true
services:
    fastapi:
        environment:
            SIGNING_KEY: 79632ce6089c52991a16fb4c6819192c534c1e9c5fdf7923c92058dada671220
            DATABASE_URL: postgresql://example_user:secret@postgres/example_db # postgresql://<<db_user>>:<<db_password>>@<<host>>/<<db_name>>.
            CORS_HOST: http://localhost:3000
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/docubash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_API_HOST: ${REACT_APP_API_HOST}

    postgres:
        image: postgres:14.5-bullseye
        volumes:
            # DB volume name = postgres-data
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: example_user
            POSTGRES_DB: example_db
        ports:
            - 15432:5432
